name: executing remote ssh commands using ssh key
uses: appleboy/ssh-action@v1.0.0
with:
  host: ${{ secrets.SSHHOST }}
  username: ${{ secrets.SSHUSER }}
  key: ${{ secrets.SSHKEY }}
  port: ${{ secrets.SSHPORT }}
  script: whoami
