name: test-aws
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSHHOST}}
          username: ${{secrets.SSHUSER}}
          key: ${{secrets.SSHKEY}}
          port: ${{secrets.SSHPORT}}
          script: bash ./scripts/ssh.sh && bash ./scripts/deploy.sh